<a href="https://colab.research.google.com/github/AbdulhameedSk/Machine-Learning/blob/main/K_Neighbors_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
#importing packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report , confusion_matrix
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

In [40]:
#Loading the data
df=load_iris()

In [41]:
#checking for first 3 rows
iris.data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [42]:
#Checking lables
df.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [43]:
x=iris.data
y=iris.target

In [44]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [47]:
knn=KNeighborsClassifier(n_neighbors=5)

In [48]:
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [49]:
y_pred=knn.predict(x_train)

In [50]:
confusion_matrix(y_train,y_pred)

array([[40,  0,  0],
       [ 0, 38,  3],
       [ 0,  1, 38]])

In [57]:
print(classification_report(y_train,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.97      0.93      0.95        41
           2       0.93      0.97      0.95        39

    accuracy                           0.97       120
   macro avg       0.97      0.97      0.97       120
weighted avg       0.97      0.97      0.97       120



In [53]:
y_pred2=knn.predict(x_test)

In [54]:
confusion_matrix(y_test,y_pred2)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [56]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

