<a href="https://colab.research.google.com/github/AbdulhameedSk/Machine-Learning/blob/main/Naive_Bayes_on_Wine_DS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_wine
from sklearn.metrics import classification_report,confusion_matrix , accuracy_score
from sklearn.model_selection import train_test_split
import sklearn.metrics as metrics

In [35]:
df=load_wine()

In [36]:
df.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [37]:
x=df.data

In [38]:
y=df.target

In [39]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [40]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()

In [41]:
nb.fit(x_train,y_train)

GaussianNB()

In [42]:
y_pred=nb.predict(x_train)
print(confusion_matrix(y_train,y_pred))
print(classification_report(y_train,y_pred))

[[43  2  0]
 [ 0 55  2]
 [ 0  0 40]]
              precision    recall  f1-score   support

           0       1.00      0.96      0.98        45
           1       0.96      0.96      0.96        57
           2       0.95      1.00      0.98        40

    accuracy                           0.97       142
   macro avg       0.97      0.97      0.97       142
weighted avg       0.97      0.97      0.97       142



In [43]:
y_pred2=nb.predict(x_test)
print(confusion_matrix(y_test,y_pred2))
print(classification_report(y_test,y_pred2))

[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        14
           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [44]:
print("Accuracy:", metrics.accuracy_score(y_test, y_pred2))


Accuracy: 1.0
